version: '3'

services:
    backend:
        build: ./backend/docker-image-python
        ports:
            - 8000:8000
            - 4000:4000
            - 4100:4100
            - 4200:4200
            - 5000:5000
        environment:
            - CONDUIT_SECRET=test
            - FLASK_APP=/home/backend/autoapp.py
            - FLASK_DEBUG=1
        volumes:
            - ./backend:/home/backend/
        tty: true
    database:
        image: postgres
        restart: always
        ports: 
            - 5555:5432
        environment:
            POSTGRES_PASSWORD: test
    frontend:
        image: node:14.2.0-alpine3.10
        volumes:
            - ./frontend:/home/frontend
        ports:
            - 3000:3000
        tty: true
