version: '3'

services:
    flasher-dev-ubuntu:
        build: ./docker-image-ubuntu
        ports:
            - 8000:8000
            - 4000:4000
            - 4100:4100
            - 4200:4200
        environment:
            - CONDUIT_SECRET=test
            - FLASK_APP=/home/backend/autoapp.py
            - FLASK_DEBUG=1
        volumes:
            - .:/home/backend/
        tty: true
    flasher-db:
        image: postgres
        restart: always
        ports: 
            - 5555:5432
        environment:
            POSTGRES_PASSWORD: test

